name=MemoryTools
version=0.2.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Auxiliary methods for memory and buffers.
paragraph=Auxiliary methods for operating on memory and buffers, e.g. a ring buffer.
category=Other
url=https://github.com/TobiasKnauss/ArduinoLib_MemoryTools
architectures=*
